title: "Harsh Maheshwari"
# author: "Harsh Maheshwari"
author:
  name: "Your Name"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "I am an **amazing** person." # Note: Markdown is allowed
  location: "Somewhere"
  links:
    - label: "Made Mistakes"
      icon: "fas fa-fw fa-link"
      url: "https://mademistakes.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/mmistakes"
description: ""
markdown: "kramdown"
more: "read more »"
url: "https://harshm121.github.io/"
# baseurl: ""
paginate: 2
permalink: pretty
excerpt_separator: "\n\n\n" # two blank lines

style:
  minimalist: true
  dark: false

navigation:
  - index.md
  - Projects/index.md
  - Articles/index.md
  - Interests/index.md
  - CV/index.md

# comments:
#   disqus: "disqus-contrast"
# #  isso: "comments.mysite.org"

links: # see http://fontawesome.io/icons/#brand for all possible icons
  - linkedin: "https://www.linkedin.com/in/harsh-maheshwari-650039110/"
  - resume_google_scholar_url: "https://scholar.google.com/citations?user=fs01uyQAAAAJ&hl=en&oi=ao"
  - github: "https://github.com/harshm121/"
  - envelope: "mailto:harshm121@gmail.com"
  - medium: "https://medium.com/@harshm121"
  - twitter: "https://twitter.com/harsh_m121"
  - instagram: "https://www.instagram.com/harsh.maheshwari_/"
  - file: "/PDFs/HarshMaheshwari_CV.pdf"
  # - facebook: "https://www.facebook.com/harshrmaheshwari/"

defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
sass: {style: expanded}
plugins: [jekyll-feed, jekyll-paginate]
